name: untukmu
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_analytics: ^11.3.3
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  firebase_dynamic_links: ^6.0.8
  firebase_messaging: ^15.1.3
  firebase_remote_config: ^5.1.3
  firebase_storage: ^12.3.4
  flutter_riverpod: ^2.6.1
  get_it: ^8.0.2
  go_router: ^14.3.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:
  flutter_gen_runner:
  custom_lint:
  riverpod_lint:

flutter:
  generate: true
  uses-material-design: true
  assets:
    - config/
    - assets/images/
    - assets/lottie/
    - assets/icon/
    - assets/docs/
